CREATE TABLE `submissions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`submissionId` varchar(64) NOT NULL,
	`clientEmail` varchar(320) NOT NULL,
	`clientName` varchar(255) NOT NULL,
	`clientPhone` varchar(20) NOT NULL,
	`serviceType` varchar(100) NOT NULL,
	`description` text NOT NULL,
	`uploadedFileUrl` text,
	`uploadedFileKey` varchar(255),
	`status` enum('pending','processing','completed','failed') NOT NULL DEFAULT 'pending',
	`paymentStatus` enum('unpaid','paid','refunded') NOT NULL DEFAULT 'unpaid',
	`paymentMethod` varchar(50),
	`stripePaymentIntentId` varchar(255),
	`amountPaid` int,
	`ocrText` text,
	`draftedDocument` text,
	`draftedFileUrl` text,
	`draftedFileKey` varchar(255),
	`processingNotes` text,
	`emailSentAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `submissions_id` PRIMARY KEY(`id`),
	CONSTRAINT `submissions_submissionId_unique` UNIQUE(`submissionId`)
);
